[package]
name = "HyperlaneValidatorAnnounce"
version = "1.0.0"
authors = []

[addresses]
hp_validator = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
branch = "main"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.HyperlaneLibrary]
local = "../library"

[dev-dependencies]
