[package]
name = "tokens"
version = "1.0.0"
authors = []

[addresses]
tokens = "_"
hp_router = "_"
hp_library = "_"
hp_mailbox = "_"

[dev-addresses]


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.HyperlaneLibrary]
local = "../library"

[dependencies.HyperlaneISM]
local = "../isms"

[dependencies.HyperlaneMailBox]
local = "../mailbox"

[dependencies.HyperlaneRouter]
local = "../router"

[dev-dependencies]
