[package]
name = "examples"
version = "1.0.0"
authors = []

[addresses]
examples = "_"
hp_router = "0x123452"
hp_library = "0x123453"
hp_mailbox = "0x123454"

[dev-addresses]


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.HyperlaneLibrary]
local = "../library"

[dependencies.HyperlaneISM]
local = "../isms"

[dependencies.HyperlaneMailBox]
local = "../mailbox"

[dependencies.HyperlaneRouter]
local = "../router"

[dev-dependencies]
