version: "3"

environment:

processes:
  # movement:
  #   command: |
  #     exit 1
  #   readiness_probe:
  #     exec:
  #       command: echo "true"

  start-eth-chain:
    command: |
      anvil --chain-id 666 --config-out "./anvil.json" --port 4242
    readiness_probe:
      exec:
        command: echo "true"

  build-eth-contracts:
    command: |
      yarn install
      cd ../solidity && forge build
    depends_on:
      start-eth-chain:
        condition: process_healthy
    readiness_probe:
      exec:
        command: echo "true"

  deploy-eth-contracts:
    vars: 
      RPC_URL: "{{ . RPC_URL }}"
      PRIVATE_KEY: "{{ .PRIVATE_KEY }}"
      MAILBOX_ADDRESS: ""
    command: |
      cd ../solidity

      forge create --rpc-url {{ .RPC_URL }} --private-key {{ .PRIVATE_KEY }}./contracts/client/Router.sol:Router
      echo "Deployed Router.sol!"
    
      forge create --rpc-url {{ .RPC_URL }} --private-key {{ .PRIVATE_KEY }} ./contracts/client/GasRouter.sol:GasRouter
      echo "Deployed GasRouter.sol!"

      forge create --rpc-url {{ .RPC_URL }}  --private-key {{ .PRIVATE_KEY }} ./contracts/client/MailboxClient.sol:MailboxClient
      echo "Deployed MailboxClient.sol!"

      MAILBOX_ADDRESS=$(forge create --rpc-url {{ .RPC_URL }} --private-key {{ .PRIVATE_KEY }}  ./contracts/Mailbox.sol:Mailbox --constructor-args 666 | awk '/Deployed to:/ {print $3}')
      echo "Deployed Mailbox.sol! to $MAILBOX_ADDRESS"

      forge create --rpc-url {{ .RPC_URL }} --private-key {{ .PRIVATE_KEY }}  ./contracts/hooks/igp/InterchainGasPaymaster.sol:InterchainGasPaymaster
      echo "Deployed InterchainGasPaymaster.sol! (hook)"

      forge create --rpc-url {{ .RPC_URL }} --private-key {{ .PRIVATE_KEY }}  ./contracts/hooks/igp/StorageGasOracle.sol:StorageGasOracle
      echo "Deployed StorageGasOracle.sol!"

      forge create --rpc-url {{ .RPC_URL }} --private-key {{ .PRIVATE_KEY }}  ./contracts/hooks/MerkleTreeHook.sol:MerkleTreeHook --constructor-args $MAILBOX_ADDRESS
      echo "Deployed MerkleTreeHook.sol!"
      
    is_tty: true
    depends_on:
      start-eth-chain:
        condition: process_healthy
      build-eth-contracts:
        condition: process_healthy
    readiness_probe:
      exec:
        command: echo "true"

  relayer:
    command: |
      cd ../rust && cargo run -p relayer
    readiness_probe:
      exec:
        command: echo "true"

  validator:
    command: |
      cd ../rust && cargo run -p validator
    readiness_probe:
      exec:
        command: echo "true"
